"""Add user table

Revision ID: 0cbd52c5700a
Revises: 4a2658631209
Create Date: 2024-02-13 10:56:25.743934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbd52c5700a'
down_revision: Union[str, None] = '4a2658631209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'MEMBER', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVATE', 'DISABLED', name='statusenum'), nullable=False),
    sa.Column('grade', sa.Enum('FREE', 'BASIC', 'PREMIUM', name='gradeenum'), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('gree',
    sa.Column('gree_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('gree_name', sa.String(length=255), nullable=True),
    sa.Column('raw_img', sa.String(length=255), nullable=False),
    sa.Column('prompt_character', sa.String(length=255), nullable=True),
    sa.Column('prompt_age', sa.Integer(), nullable=True),
    sa.Column('prompt_mbti', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVATE', 'DISABLED', name='statusenum'), nullable=True),
    sa.Column('isFavorite', sa.Boolean(), nullable=True),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ),
    sa.PrimaryKeyConstraint('gree_id')
    )
    op.create_table('emotion_report',
    sa.Column('emotion_report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gree_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('emotion_type', sa.Enum('GREE_TALK', 'USER_TALK', name='logtypeenum'), nullable=False),
    sa.Column('talk', sa.String(length=255), nullable=True),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.Column('test', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gree_id'], ['gree.gree_id'], ),
    sa.PrimaryKeyConstraint('emotion_report_id')
    )
    op.create_table('greefile',
    sa.Column('greefile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gree_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('YAML', 'GIF', 'IMG', name='filetypeenum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=255), nullable=False),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gree_id'], ['gree.gree_id'], ),
    sa.PrimaryKeyConstraint('greefile_id')
    )
    op.create_table('log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gree_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.Enum('GREE_TALK', 'USER_TALK', name='logtypeenum'), nullable=False),
    sa.Column('talk', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gree_id'], ['gree.gree_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('greefile')
    op.drop_table('emotion_report')
    op.drop_table('gree')
    op.drop_table('member')
    # ### end Alembic commands ###
