"""Add table

Revision ID: 4e23c83c8c74
Revises: 0cbd52c5700a
Create Date: 2024-02-13 10:59:53.366709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e23c83c8c74'
down_revision: Union[str, None] = '0cbd52c5700a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotion_report', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion_report', sa.Column('test', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
