"""Add table

Revision ID: 91a68635be52
Revises: 64c44508b57e
Create Date: 2024-02-13 17:26:46.547023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91a68635be52'
down_revision: Union[str, None] = '64c44508b57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotion_report', 'emotion_report_detect_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion_report', sa.Column('emotion_report_detect_test', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
