scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/GreeChar/char_cfg.yaml
      motion_cfg: examples/config/motion/dab.yaml
      retarget_cfg: examples/config/retarget/fair1_ppf.yaml

controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: temp/dab.gif